import React, { useEffect, useRef, useState } from "react";
import { fetch, appUrl, mediaUrl } from "../shared/api.js";
import { dateKeyForTimeZone } from "../shared/datetime.js";
import { StoryReplay } from "./StoryReplay.jsx";
import "./storylines.css";

async function request(path, method = "GET", body, signal) {
  const response = await fetch(path, { method, signal, ...(body ? { headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) } : {}) });
  const data = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(typeof data.detail === "string" ? data.detail : `Request failed (${response.status}). Refresh and retry.`);
  return data;
}
function memberFor(id) { return { incident_id: id, subject_ids: [], relationship: "related_event", note: "" }; }

export function StorylinesPage({ timeZone, canEdit = false }) {
  const initial = new URLSearchParams(window.location.search);
  const [stories, setStories] = useState([]), [total, setTotal] = useState(0), [storyPage, setStoryPage] = useState(0);
  const [storyId, setStoryId] = useState(initial.get("story") || ""), [story, setStory] = useState(null);
  const [title, setTitle] = useState(""), [summary, setSummary] = useState(""), [members, setMembers] = useState([]);
  const [day, setDay] = useState(dateKeyForTimeZone(Date.now(), timeZone)), [camera, setCamera] = useState("");
  const [incidents, setIncidents] = useState([]), [incidentTotal, setIncidentTotal] = useState(0), [incidentPage, setIncidentPage] = useState(0), [cameraOptions, setCameraOptions] = useState([]);
  const [picked, setPicked] = useState(() => new Set(initial.get("incident") ? [initial.get("incident")] : []));
  const [suggestions, setSuggestions] = useState(null), [plan, setPlan] = useState(null), [directed, setDirected] = useState(true), [split, setSplit] = useState(true), [order, setOrder] = useState("chronological");
  const [busy, setBusy] = useState(""), [error, setError] = useState(""), [notice, setNotice] = useState(""), [loading, setLoading] = useState(false);
  const [mergeId, setMergeId] = useState("");
  const selectedRef = useRef(storyId); selectedRef.current = storyId;
  function apply(data) { setStory(data); setTitle(data.title); setSummary(data.summary || ""); setMembers(data.members); setPlan(null); setSuggestions(null); }
  async function refreshStories() { const data = await request(`/api/storylines?limit=50&offset=${storyPage * 50}`); setStories(data.items); setTotal(data.total); }
  useEffect(() => { const controller = new AbortController(); void request(`/api/storylines?limit=50&offset=${storyPage * 50}`, "GET", undefined, controller.signal).then((data) => { setStories(data.items); setTotal(data.total); }).catch((e) => { if (e.name !== "AbortError") setError(e.message); }); return () => controller.abort(); }, [storyPage]);
  useEffect(() => {
    const controller = new AbortController(); setError(""); setNotice(""); setStory(null); setPlan(null); setSuggestions(null);
    window.history.replaceState(null, "", appUrl(`/storylines${storyId ? `?story=${encodeURIComponent(storyId)}` : ""}`));
    if (storyId) { setLoading(true); void request(`/api/storylines/${storyId}`, "GET", undefined, controller.signal).then(apply).catch((e) => { if (e.name !== "AbortError") setError(e.message); }).finally(() => { if (!controller.signal.aborted) setLoading(false); }); }
    return () => controller.abort();
  }, [storyId]);
  useEffect(() => {
    const controller = new AbortController();
    void request(`/api/incidents/search?${new URLSearchParams({ day, time_zone: timeZone, event_type: "all", limit: 25, offset: incidentPage * 25, camera_id: camera })}`, "GET", undefined, controller.signal)
      .then((data) => { setIncidents(data.items || []); setIncidentTotal(data.total || 0); setCameraOptions(data.facets?.camera_ids || []); })
      .catch((e) => { if (e.name !== "AbortError") setError(e.message); });
    return () => controller.abort();
  }, [day, timeZone, incidentPage, camera]);
  async function run(label, operation) { setBusy(label); setError(""); setNotice(""); try { await operation(); } catch (e) { setError(e.message); } finally { setBusy(""); } }
  async function save(nextMembers = members) {
    const data = await request(`/api/storylines/${story.id}`, "PUT", { revision: story.revision, title: title.trim() || "Untitled Storyline", summary, members: nextMembers });
    apply(data); await refreshStories();
  }
  async function create() {
    const data = await request("/api/storylines", "POST", { title: "New Storyline", summary: "", members: [...picked].map(memberFor) });
    setStoryId(data.id); setPicked(new Set()); await refreshStories();
  }
  const dirty = Boolean(story && (title !== story.title || summary !== story.summary || JSON.stringify(members) !== JSON.stringify(story.members)));
  const locked = Boolean(busy || loading);
  function move(index, delta) { setMembers((previous) => { const next = [...previous]; [next[index], next[index + delta]] = [next[index + delta], next[index]]; return next; }); }
  function patchMember(index, changes) { setMembers((previous) => previous.map((m, n) => n === index ? { ...m, ...changes } : m)); }
  const options = { revision: story?.revision, directed, split_screen: split, order };
  const names = new Map((story?.incidents || []).flatMap((i) => [i.id, ...(i.story_member_ids || [])].map((id) => [id, i])));
  const freshReview = story?.ai_review && !story.ai_review_stale ? story.ai_review : null;
  return <main className="storylines-page">
    <header className="storylines-heading"><div><h2>Storylines</h2><p>Connected incidents. One account of what happened. One replay.</p></div><button disabled={locked} onClick={() => void run("Refreshing", async () => { await refreshStories(); if (storyId) apply(await request(`/api/storylines/${storyId}`)); })}>Refresh</button></header>
    {error ? <p role="alert" className="story-error">{error}</p> : null}{notice ? <p role="status">{notice}</p> : null}{busy ? <p role="status" aria-live="polite">{busy}…</p> : null}
    <div className="storylines-layout">
      <aside className="story-panel story-library"><h3>Saved Storylines</h3>{stories.map((item) => <button disabled={locked || dirty} aria-current={storyId === item.id ? "true" : undefined} key={item.id} onClick={() => setStoryId(item.id)}><strong>{item.title}</strong><span>{item.members.length} incidents · {new Date(item.updated_at * 1000).toLocaleString(undefined, { timeZone })}</span></button>)}{!stories.length ? <p>No saved Storylines. Select incidents to create one.</p> : null}<div className="story-controls"><button disabled={!storyPage || locked} onClick={() => setStoryPage((p) => p - 1)}>Previous</button><span>{storyPage + 1} / {Math.max(1, Math.ceil(total / 50))}</span><button disabled={(storyPage + 1) * 50 >= total || locked} onClick={() => setStoryPage((p) => p + 1)}>Next</button></div></aside>
      <section className="story-panel story-editor" aria-busy={locked}>
        {loading ? <p>Loading Storyline…</p> : !story ? <div className="story-empty"><h3>Build the complete event</h3><p>Select incidents in the evidence browser, then create a Storyline. You can add related cameras, review AI suggestions, and replay or export the sequence.</p></div> : <>
          <label>Title<input maxLength={120} disabled={!canEdit || locked} value={title} onChange={(e) => setTitle(e.target.value)} /></label>
          <label>Context<textarea maxLength={2000} disabled={!canEdit || locked} value={summary} onChange={(e) => setSummary(e.target.value)} placeholder="Describe the event and any context you know." /></label>
          {canEdit ? <div className="story-controls"><button disabled={locked || !dirty || !members.length} onClick={() => void run("Saving", () => save())}>Save changes</button><button disabled={locked || !dirty} onClick={() => apply(story)}>Discard edits</button></div> : null}
          {dirty ? <p>Save changes before generating suggestions or replay.</p> : null}
          <h3>Incident sequence</h3><ol className="story-members">{members.map((member, index) => { const incident = names.get(member.incident_id); return <li key={member.incident_id}><div><a href={appUrl(`/incidents?incident_id=${encodeURIComponent(member.incident_id)}`)}>{incident ? `${incident.camera_ids?.join(" / ") || incident.camera_id} · ${incident.summary || incident.labels?.join(", ")}` : "Incident unavailable"}</a><small>{incident?.start_at ? new Date(incident.start_at).toLocaleString(undefined, { timeZone }) : member.incident_id}</small></div>
            {canEdit ? <><select aria-label={`Relationship for incident ${index + 1}`} disabled={locked} value={member.relationship} onChange={(e) => patchMember(index, { relationship: e.target.value })}><option value="related_event">Related event</option><option value="same_subject">Same subject, operator confirmed</option><option value="context">Context only</option></select><label>Focus<select disabled={locked} value={member.subject_ids[0] || ""} onChange={(e) => patchMember(index, { subject_ids: e.target.value ? [e.target.value] : [] })}><option value="">All observed subjects</option>{(incident?.subjects || []).map((s) => <option key={s.id} value={s.id}>{s.label} · {s.id.slice(-6)}</option>)}</select></label><input aria-label={`Note for incident ${index + 1}`} maxLength={500} value={member.note} disabled={locked} onChange={(e) => patchMember(index, { note: e.target.value })} placeholder="Connection or context" /><div className="story-controls"><button aria-label={`Move incident ${index + 1} up`} disabled={locked || index === 0} onClick={() => move(index, -1)}>↑</button><button aria-label={`Move incident ${index + 1} down`} disabled={locked || index === members.length - 1} onClick={() => move(index, 1)}>↓</button><button disabled={locked || members.length === 1} onClick={() => setMembers((m) => m.filter((_, n) => n !== index))}>Remove</button><button disabled={locked || dirty || members.length < 2} onClick={() => void run("Splitting", async () => { const data = await request(`/api/storylines/${story.id}/split`, "POST", { revision: story.revision, incident_ids: [member.incident_id] }); apply(await request(`/api/storylines/${data.story.id}`)); await refreshStories(); })}>Split out</button></div></> : <span>{member.relationship.replaceAll("_", " ")} · {member.note}</span>}
          </li>; })}</ol>
          <div className="story-controls"><label><input type="checkbox" checked={directed} disabled={locked} onChange={(e) => { setDirected(e.target.checked); setPlan(null); }} />Automatic zoom</label><label><input type="checkbox" checked={split} disabled={locked} onChange={(e) => { setSplit(e.target.checked); setPlan(null); }} />Split-screen overlap</label><label>Replay order<select value={order} disabled={locked} onChange={(e) => { setOrder(e.target.value); setPlan(null); }}><option value="chronological">Chronological</option><option value="member">My sequence</option></select></label></div>
          <div className="story-controls"><button disabled={locked || dirty} onClick={() => void run("Preparing replay", async () => setPlan(await request(`/api/storylines/${story.id}/replay`, "POST", options)))}>Prepare Story Replay</button>{canEdit ? <><button disabled={locked || dirty} onClick={() => void run("Queueing export", async () => { await request(`/api/storylines/${story.id}/export`, "POST", options); setNotice("Story Replay export queued. Track progress and download it in Exports."); })}>Export MP4</button><a href={appUrl("/exports")}>Open Exports</a></> : null}</div>
          {plan ? <StoryReplay plan={plan} /> : null}
          {canEdit ? <div className="story-controls"><button disabled={locked || dirty} onClick={() => void run("Finding related incidents", async () => setSuggestions(await request(`/api/storylines/${story.id}/suggestions`)))}>Suggest related incidents</button><button disabled={locked || dirty} onClick={() => void run("Reviewing with configured AI", async () => apply(await request(`/api/storylines/${story.id}/ai`, "POST", { revision: story.revision })))}>AI title & context</button></div> : null}
          {story.ai_review_stale ? <p className="story-warning">Incident evidence changed. Re-run AI review before using its conclusions.</p> : null}
          {freshReview ? <section className="story-ai"><h3>{freshReview.title}</h3><p>{freshReview.summary}</p>{freshReview.actions.map((a, index) => <p key={index}><strong>{a.certainty === "possible" ? "Possible: " : "Observed: "}</strong>{a.description} {a.incident_ids.map((id) => <a key={id} href={appUrl(`/incidents?incident_id=${encodeURIComponent(id)}`)}>Evidence </a>)}</p>)}{freshReview.suggested_relationships.map((r, index) => <p key={index}><strong>Proposed connection:</strong> {r.explanation} <a href={appUrl(`/incidents?incident_id=${encodeURIComponent(r.left)}`)}>First incident</a> · <a href={appUrl(`/incidents?incident_id=${encodeURIComponent(r.right)}`)}>Second incident</a></p>)}{canEdit ? <button disabled={locked} onClick={() => { setTitle(freshReview.title); setSummary(freshReview.summary); }}>Use AI title and summary</button> : null}<small>{freshReview.provider} · {freshReview.model || "Configured default"} · {freshReview.reviewed_incident_ids.length} incident images reviewed</small></section> : null}
          {suggestions ? <section><h3>Connection suggestions</h3><p>High, moderate and low describe evidence strength. Each connection remains reviewable.</p>{suggestions.anchors_truncated ? <p>Only the first eight selected incidents were searched.</p> : null}{!suggestions.items.length ? <p>No additional candidates found in the bounded search windows.</p> : null}{suggestions.items.map((s) => <article className="story-suggestion" key={s.incident.id}><a href={appUrl(`/incidents?incident_id=${encodeURIComponent(s.incident.id)}`)}>{s.incident.camera_id} · {s.incident.summary}</a><strong>{s.confidence} confidence · {s.match_strength.replaceAll("_", " ")}</strong><p>{s.reasons.join("; ")}</p>{s.route ? <small>Route: {s.route.route_name}</small> : null}<div className="story-controls">{s.dismissed ? <span>Dismissed for this evidence version</span> : <button disabled={locked} onClick={() => void run("Adding connection", async () => apply(await request(`/api/storylines/${story.id}/suggestions`, "POST", { revision: story.revision, incident_id: s.incident.id, evidence_fingerprint: s.evidence_fingerprint, decision: "accept" })))}>Add as related event</button>}<button disabled={locked} onClick={() => void run("Updating suggestion", async () => { const data = await request(`/api/storylines/${story.id}/suggestions`, "POST", { revision: story.revision, incident_id: s.incident.id, evidence_fingerprint: s.evidence_fingerprint, decision: s.dismissed ? "reset" : "reject" }); apply(data); setSuggestions(await request(`/api/storylines/${story.id}/suggestions`)); })}>{s.dismissed ? "Restore suggestion" : "Dismiss"}</button></div></article>)}</section> : null}
          {canEdit ? <details><summary>Merge or delete Storyline</summary><div className="story-controls"><select aria-label="Storyline to merge" value={mergeId} disabled={locked || dirty} onChange={(e) => setMergeId(e.target.value)}><option value="">Choose another Storyline</option>{stories.filter((s) => s.id !== story.id).map((s) => <option key={s.id} value={s.id}>{s.title}</option>)}</select><button disabled={locked || dirty || !mergeId} onClick={() => void run("Merging", async () => { const source = await request(`/api/storylines/${mergeId}`); apply(await request(`/api/storylines/${story.id}/merge`, "POST", { revision: story.revision, source_id: mergeId, source_revision: source.revision })); setMergeId(""); await refreshStories(); })}>Merge into this Storyline</button><button disabled={locked} onClick={() => { if (window.confirm("Delete this Storyline? Original incidents and exported videos remain available.")) void run("Deleting", async () => { await request(`/api/storylines/${story.id}?revision=${story.revision}`, "DELETE"); setStoryId(""); await refreshStories(); }); }}>Delete Storyline</button></div></details> : null}
        </>}
      </section>
      <aside className="story-panel story-browser"><h3>Evidence browser</h3><label>Day<input type="date" value={day} disabled={locked} onChange={(e) => { setDay(e.target.value); setIncidentPage(0); }} /></label><label>Camera<select value={camera} disabled={locked} onChange={(e) => { setCamera(e.target.value); setIncidentPage(0); }}><option value="">All cameras</option>{cameraOptions.map((id) => <option key={id}>{id}</option>)}</select></label>
        {canEdit ? <><div className="story-controls"><button disabled={locked || !picked.size || picked.size > 64} onClick={() => void run("Creating Storyline", create)}>Create from {picked.size} selected</button>{story ? <button disabled={locked || dirty || !picked.size} onClick={() => void run("Adding incidents", async () => { const existing = new Set(members.map((m) => m.incident_id)); await save([...members, ...[...picked].filter((id) => !existing.has(id)).map(memberFor)]); setPicked(new Set()); })}>Add to current</button> : null}<button disabled={locked || !picked.size} onClick={() => setPicked(new Set())}>Clear selection</button></div></> : null}
        {!incidents.length ? <p>No incidents for these filters.</p> : null}{incidents.map((i) => <article className="story-evidence" key={i.id}>{canEdit ? <label><input type="checkbox" checked={picked.has(i.id)} disabled={locked} onChange={(e) => setPicked((current) => { const next = new Set(current); if (e.target.checked) next.add(i.id); else next.delete(i.id); return next; })} />Select incident</label> : null}<a href={appUrl(`/incidents?incident_id=${encodeURIComponent(i.id)}`)}>{i.snapshot_url ? <img loading="lazy" alt={`${i.camera_id} incident`} src={mediaUrl(i.snapshot_url)} /> : null}<strong>{i.camera_id} · {i.summary || i.labels?.join(", ")}</strong></a><small>{new Date(i.start_at).toLocaleString(undefined, { timeZone })}</small></article>)}<div className="story-controls"><button disabled={!incidentPage || locked} onClick={() => setIncidentPage((p) => p - 1)}>Previous</button><span>{incidentPage + 1} / {Math.max(1, Math.ceil(incidentTotal / 25))}</span><button disabled={(incidentPage + 1) * 25 >= incidentTotal || locked} onClick={() => setIncidentPage((p) => p + 1)}>Next</button></div>
      </aside>
    </div>
  </main>;
}
